/* 
Name : SobjectPurgeController
CreatedDate : 29-OCT-2023
CreatedBy Name : Sachin Gaikwad
Description : Demo class for git operation
Date           Developer Name    Description
29-OCT-23       Sachin Gaikwad    First changes
30-OCT-23       Sachin Gaikwad    modified constractor changes
*/

public with sharing class DemoApexClassFromGit {

//create class in gitHub.
//created contructor
public static DemoApexClassFromGit(){

}
}
