/* 
Name : SobjectPurgeController
CreatedDate : 29-OCT-2023
CreatedBy Name : Sachin Gaikwad
Description : Handling the data communication between Apex and cmp_SobjectPurgeData LWC components. 
Date           Developer Name    Description
29-10-23       Sachin Gaikwad    First changes
*/

public with sharing class DemoApexClassFromGit {

//create class in gitHub.
//created contructor
public static DemoApexClassFromGit(){

}
}
